## provide the name of the namespace
namespace:
  name: staging

## define the image to execute with the Deployment 
image:
  repository: nginx
  tag: 1.18.0
  imagePullPolicy: IfNotPresent

## set the number of replicas for an application 
replicaCount: 1

resources:
  request:
    memory: "128Mi"
    cpu: "50m"
  
configmap:
  data:
    version: "1.18.0"