## provide the name of the namespace
namespace:
  name: demo

## define the image to execute with the Deployment 
image:
  name: nginx-alpine
  tag: alpine
  imagePullPolicy: IfNotPresent

## set the number of replicas for an application 
replicaCount: 3

resources:
  request:
    memory: "256Mi"
    cpu: "50m"
  
service:
  port: 8111
  type: ClusterIP
  
configmap:
  data:
    version: "alpine"