apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-alpine-staging
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://kubernetes.default.svc
  project: default
  source:
    ## change the source of manifests to a Helm chart
    helm:
      ## define the input values file
      valueFiles:
      - values-staging.yaml
    ## set the path to the folder where the Helm chart is stored
    path: my-solutions/helm-l5s17
    ## set the base repository that contains the Helm chart
    repoURL: https://github.com/ebomitali/nd064_course_1 
    targetRevision: HEAD
  # Sync policy
  syncPolicy: {}